// data.js — New Horizons 6 content
// Grammar practice, response matching, writing items for all 8 units

'use strict';

const NH6_UNITS = [
  { id:1, title:'This is me!',         titleJa:'じこしょうかいをしよう',   emoji:'👋', color:'#1565C0', vocabCats:'colors,sports,animals,things,family' },
  { id:2, title:'My Daily Schedule',   titleJa:'一日の生活を伝えよう',      emoji:'⏰', color:'#2E7D32', vocabCats:'daily,time,weather' },
  { id:3, title:'My Weekend',          titleJa:'週末にしたことを伝えよう',  emoji:'🏆', color:'#C62828', vocabCats:'food,actions,descriptions,sports' },
  { id:4, title:'Let\'s see the world.', titleJa:'行きたい国を紹介しよう', emoji:'🌍', color:'#6A1B9A', vocabCats:'nature,descriptions,food' },
  { id:5, title:'Where is it from?',   titleJa:'持ち物の国を紹介しよう',   emoji:'🗺️', color:'#E65100', vocabCats:'things,stationery,clothes,ingredients' },
  { id:6, title:'Save the animals.',   titleJa:'動物を守るために伝えよう', emoji:'🐘', color:'#1B5E20', vocabCats:'animals,sea-animals,nature' },
  { id:7, title:'My Best Memory',      titleJa:'一番の思い出を伝えよう',   emoji:'📸', color:'#880E4F', vocabCats:'events,food,town,descriptions' },
  { id:8, title:'My Future, My Dream', titleJa:'将来の夢を伝えよう',       emoji:'⭐', color:'#0D47A1', vocabCats:'jobs,clubs,actions,descriptions' },
];

// ── GRAMMAR PRACTICE ─────────────────────────────────────────────────────
// Format: prompt (with ___ blank), choices[4], correct index, hint
const NH6_GRAMMAR = {
  1: [
    { prompt:'I ___ soccer.',                     choices:['like','liked','liking','am like'],         correct:0, hint:'好きだ → like' },
    { prompt:'I ___ basketball.',                 choices:['like','want be','am liking','goes'],       correct:0, hint:'スポーツが好き → I like + sport' },
    { prompt:'I\'m good ___ swimming.',           choices:['at','to','in','for'],                      correct:0, hint:'得意 → good at' },
    { prompt:'I\'m good at ___ the recorder.',    choices:['playing','play','played','plays'],         correct:0, hint:'good at + V-ing' },
    { prompt:'My treasure ___ this bag.',         choices:['is','am','are','was'],                     correct:0, hint:'My treasure is...' },
    { prompt:'___ treasure is this comic book.',  choices:['My','I','Me','Mine'],                      correct:0, hint:'私の宝物' },
    { prompt:'It\'s from ___ mother.',            choices:['my','I','me','mine'],                      correct:0, hint:'〜から = from + 人' },
    { prompt:'It\'s ___ my grandfather.',         choices:['from','to','at','in'],                     correct:0, hint:'〜からもらった → from' },
    { prompt:'I like ___.',                       choices:['blue','bluing','to blue','blues'],         correct:0, hint:'I like + 色' },
    { prompt:'___ is your treasure?',             choices:['What','Where','Who','When'],               correct:0, hint:'「何？」と聞く → What' },
    { prompt:'This is ___ sweatshirt.',           choices:['my','I','me','mine'],                      correct:0, hint:'これは私の… → This is my' },
    { prompt:'I\'m good at ___.',                 choices:['dancing','dance','danced','to dance'],     correct:0, hint:'good at + V-ing' },
  ],
  2: [
    { prompt:'I ___ get up at 6 a.m.',            choices:['always','went','want','liked'],            correct:0, hint:'いつも → always' },
    { prompt:'I ___ play basketball.',            choices:['sometimes','went to','liked to','going'],  correct:0, hint:'ときどき → sometimes' },
    { prompt:'I ___ go to bed at 9 p.m.',         choices:['usually','usually to','want be','is'],     correct:0, hint:'たいてい → usually' },
    { prompt:'I ___ wash the dishes.',            choices:['never','not','no','isn\'t'],               correct:0, hint:'けっして〜ない → never' },
    { prompt:'I get up ___ 6 a.m.',               choices:['at','in','on','by'],                       correct:0, hint:'何時に → at + 時間' },
    { prompt:'I usually go to bed ___ 9 p.m.',    choices:['at','in','on','to'],                       correct:0, hint:'何時に → at' },
    { prompt:'I sometimes play tennis ___ 3 p.m.',choices:['at','in','on','by'],                       correct:0, hint:'3時に → at 3 p.m.' },
    { prompt:'___ time do you get up?',           choices:['What','Which','Where','When'],             correct:0, hint:'「何時？」→ What time' },
    { prompt:'I ___ walk my dog at 5 p.m.',       choices:['usually','went','liked','is'],             correct:0, hint:'たいてい → usually' },
    { prompt:'I always get ___ at 6 a.m.',        choices:['up','out','on','in'],                      correct:0, hint:'起きる → get up' },
    { prompt:'I ___ watch TV at 8 p.m.',          choices:['sometimes','sometime','some time','any'],  correct:0, hint:'ときどき → sometimes' },
    { prompt:'I never ___ the dishes.',           choices:['wash','washing','washed','washer'],        correct:0, hint:'洗う → wash' },
  ],
  3: [
    { prompt:'I ___ to the stadium.',             choices:['went','go','goes','going'],                correct:0, hint:'過去形 went ← go' },
    { prompt:'I ___ fried chicken.',              choices:['ate','eat','eats','eating'],               correct:0, hint:'過去形 ate ← eat' },
    { prompt:'I ___ a baseball game.',            choices:['enjoyed watching','enjoy watch','enjoying to watch','watched enjoy'], correct:0, hint:'楽しんだ → enjoyed watching' },
    { prompt:'It ___ great.',                     choices:['was','is','were','be'],                    correct:0, hint:'過去形 was ← is' },
    { prompt:'I ___ soccer with my brother.',     choices:['played','play','plays','playing'],         correct:0, hint:'過去形 played ← play' },
    { prompt:'I ___ at Koshien Stadium.',         choices:['went to','goes to','going to','go'],       correct:0, hint:'〜に行った → went to' },
    { prompt:'How ___ your weekend?',             choices:['was','is','were','be'],                    correct:0, hint:'週末はどうでしたか？' },
    { prompt:'I ___ pudding.',                    choices:['ate','eat','eating','eaten'],              correct:0, hint:'食べた → ate' },
    { prompt:'It was ___.',                       choices:['great','go','went','good at'],             correct:0, hint:'すごかった → great' },
    { prompt:'I ___ a rugby game.',               choices:['watched','watch','watching','watches'],    correct:0, hint:'過去形 watched ← watch' },
    { prompt:'I enjoyed ___ a rugby game.',       choices:['watching','watch','watched','watches'],    correct:0, hint:'enjoyed + V-ing' },
    { prompt:'___ was your weekend?',             choices:['How','What','Where','When'],               correct:0, hint:'週末はどうでしたか？' },
  ],
  4: [
    { prompt:'Let\'s go ___ France.',             choices:['to','in','at','for'],                      correct:0, hint:'〜へ行こう → go to' },
    { prompt:'You can ___ the Eiffel Tower.',     choices:['see','seeing','saw','seen'],               correct:0, hint:'〜できる → can + 動詞の原形' },
    { prompt:'You can ___ pizza in Italy.',       choices:['eat','eating','ate','eaten'],              correct:0, hint:'can + 動詞の原形' },
    { prompt:'___ is beautiful.',                 choices:['It','Its','Is','This is'],                 correct:0, hint:'それは〜だ → It is' },
    { prompt:'France ___ a nice country.',        choices:['is','are','am','be'],                     correct:0, hint:'France is...' },
    { prompt:'You can ___ a famous museum.',      choices:['visit','visiting','visited','visits'],     correct:0, hint:'can + 動詞の原形' },
    { prompt:'I want ___ go to America.',         choices:['to','at','in','for'],                      correct:0, hint:'したい → want to' },
    { prompt:'You can ___ big hamburgers.',       choices:['eat','ate','eating','eaten'],              correct:0, hint:'can + 動詞の原形' },
    { prompt:'___ can you do in China?',          choices:['What','Where','When','Who'],               correct:0, hint:'何ができる？ → What' },
    { prompt:'Let\'s go to ___.',                 choices:['Australia','Australias','the Australia','a Australia'], correct:0, hint:'国名に a/the はつかない' },
    { prompt:'It\'s ___.',                        choices:['beautiful','beauty','beautify','beauteous'], correct:0, hint:'美しい → beautiful' },
    { prompt:'___ do you want to go?',            choices:['Where','What','When','Who'],               correct:0, hint:'どこに？ → Where' },
  ],
  5: [
    { prompt:'This ___ from Germany.',            choices:['is','are','am','be'],                      correct:0, hint:'これは〜だ → This is' },
    { prompt:'It\'s ___ New Zealand.',            choices:['from','in','at','to'],                     correct:0, hint:'〜からの → from' },
    { prompt:'___ is it from?',                   choices:['Where','What','Which','When'],             correct:0, hint:'どこから？ → Where' },
    { prompt:'Vietnam ___ in Asia.',              choices:['is','are','am','be'],                      correct:0, hint:'Vietnam is...' },
    { prompt:'My sweater is ___ New Zealand.',    choices:['from','in','at','to'],                     correct:0, hint:'〜産 → from' },
    { prompt:'This is ___ cap.',                  choices:['my','I','me','mine'],                      correct:0, hint:'私の帽子 → my cap' },
    { prompt:'New Zealand is ___ Oceania.',       choices:['in','at','on','from'],                     correct:0, hint:'〜にある → is in' },
    { prompt:'Is ___ from Japan?',               choices:['this','these','those','its'],              correct:0, hint:'これは〜ですか？ → Is this...' },
    { prompt:'___ is your glue from?',            choices:['Where','What','When','Who'],               correct:0, hint:'どこから？ → Where' },
    { prompt:'My sandwich ___ a COT sandwich.',   choices:['is','are','am','be'],                      correct:0, hint:'My sandwich is...' },
    { prompt:'It\'s ___ Vietnam.',                choices:['from','to','at','in'],                     correct:0, hint:'〜からの → from' },
    { prompt:'This ___ my sweatshirt.',           choices:['is','are','am','be'],                      correct:0, hint:'これは私の〜 → This is' },
  ],
  6: [
    { prompt:'Tigers ___ in forests.',            choices:['live','lives','lived','living'],           correct:0, hint:'住んでいる → live' },
    { prompt:'Hunting ___ a big problem.',        choices:['is','are','am','be'],                      correct:0, hint:'Hunting is...' },
    { prompt:'We ___ use eco-friendly bags.',     choices:['can','could','want','like'],               correct:0, hint:'〜できる → can' },
    { prompt:'We can ___ plastic bags.',          choices:['reuse','reusing','reused','reuses'],       correct:0, hint:'can + 動詞の原形' },
    { prompt:'___ loss is a big problem.',        choices:['Forest','Foresting','Forests','Forested'], correct:0, hint:'森林破壊 → forest loss' },
    { prompt:'Let\'s save the ___.',              choices:['tigers','tigering','tigered','tiger'],     correct:0, hint:'複数形の tigers' },
    { prompt:'Sea turtles live ___ the sea.',     choices:['in','at','on','by'],                       correct:0, hint:'海の中に → in the sea' },
    { prompt:'Plastic ___ a big problem.',        choices:['is','are','am','be'],                      correct:0, hint:'Plastic is...' },
    { prompt:'We ___ reuse plastic bags.',        choices:['can','cans','could to','are can'],         correct:0, hint:'〜できる → can' },
    { prompt:'Pandas live ___ forests.',          choices:['in','at','on','by'],                       correct:0, hint:'〜の中に → in' },
    { prompt:'Where ___ lions live?',             choices:['do','does','did','is'],                    correct:0, hint:'どこに住んでいる？ → Where do...' },
    { prompt:'Global warming ___ a big problem.', choices:['is','are','am','were'],                   correct:0, hint:'Global warming is...' },
  ],
  7: [
    { prompt:'My best memory ___ our school trip.', choices:['is','are','am','be'],                   correct:0, hint:'My best memory is...' },
    { prompt:'We ___ to Kyoto.',                  choices:['went','go','goes','going'],                correct:0, hint:'過去形 went ← go' },
    { prompt:'It ___ fantastic.',                 choices:['was','is','were','be'],                    correct:0, hint:'過去形 was ← is' },
    { prompt:'We ___ ice cream.',                 choices:['ate','eat','eating','eaten'],              correct:0, hint:'過去形 ate ← eat' },
    { prompt:'We ___ many temples.',              choices:['saw','see','sees','seeing'],               correct:0, hint:'過去形 saw ← see' },
    { prompt:'How ___ Todaiji Temple?',           choices:['was','is','were','be'],                    correct:0, hint:'どうでしたか？ → How was' },
    { prompt:'It was ___ and great.',             choices:['old','older','olds','oldest'],             correct:0, hint:'古くて → old' },
    { prompt:'___ your best memory?',             choices:['What\'s','Where\'s','When\'s','Who\'s'],  correct:0, hint:'何ですか？ → What is' },
    { prompt:'We went to a ___ factory.',         choices:['car','cared','caring','cars'],             correct:0, hint:'車工場 → car factory' },
    { prompt:'My best memory ___ our drama festival.', choices:['is','are','am','be'],                correct:0, hint:'My best memory is...' },
    { prompt:'It was ___.',                       choices:['fantastic','fantasticly','fanstastic','fantasy'], correct:0, hint:'すばらしかった → fantastic' },
    { prompt:'We saw ___ animals.',               choices:['many','much','more','a lot'],              correct:0, hint:'たくさんの → many + 複数形' },
  ],
  8: [
    { prompt:'I want to ___ a doctor.',           choices:['be','am','is','was'],                      correct:0, hint:'〜になりたい → want to be' },
    { prompt:'I want ___ be a teacher.',          choices:['to','at','in','for'],                      correct:0, hint:'want to + 動詞' },
    { prompt:'I want to join ___ chorus.',        choices:['the','a','an','—'],                        correct:0, hint:'部活 → join the + 部活名' },
    { prompt:'I\'m good at ___.',                 choices:['singing','sing','sang','sings'],           correct:0, hint:'good at + V-ing' },
    { prompt:'I want to ___ science.',            choices:['study','studying','studied','studies'],    correct:0, hint:'want to + 動詞の原形' },
    { prompt:'I want to ___ people in Africa.',   choices:['help','helping','helped','helps'],         correct:0, hint:'want to + 動詞の原形' },
    { prompt:'What do you want ___ be?',          choices:['to','at','in','for'],                      correct:0, hint:'want to be' },
    { prompt:'___ club do you want to join?',     choices:['What','Where','Which','Who'],              correct:0, hint:'どの部活？ → What club' },
    { prompt:'I want to work ___ Australia.',     choices:['in','at','on','by'],                       correct:0, hint:'〜で働く → work in' },
    { prompt:'I want to be an international ___.',choices:['businessperson','business','businessman','businesspeople'], correct:0, hint:'ビジネスパーソン' },
    { prompt:'I\'m good at ___.',                 choices:['playing the piano','play the piano','played the piano','plays piano'], correct:0, hint:'good at + V-ing' },
    { prompt:'I want to ___ the English club.',   choices:['join','joining','joined','joins'],         correct:0, hint:'want to + 動詞の原形' },
  ],
};

// ── RESPONSE PRACTICE ────────────────────────────────────────────────────
// Format: q (question), choices[4], correct index
const NH6_RESPONSE = {
  1: [
    { q:'What color do you like?',                choices:['I like blue.','I want blue.','I went blue.','Blue is like.'],                             correct:0 },
    { q:'What sport do you like?',                choices:['I like soccer.','I want soccer.','I went soccer.','Soccer is like.'],                     correct:0 },
    { q:'Are you good at badminton?',             choices:['Yes, I am.','Yes, I like.','Yes, I do.','Yes, I was.'],                                   correct:0 },
    { q:'What\'s your treasure?',                 choices:['My treasure is this bag.','I treasure this bag.','This bag treasure is.','I like treasure.'], correct:0 },
    { q:'Where is your treasure from?',           choices:['It\'s from my mother.','It is my mother.','From I my mother.','My mother from it.'],      correct:0 },
    { q:'What animal do you like?',               choices:['I like koalas.','I want koalas.','I went koalas.','Koalas are like.'],                     correct:0 },
    { q:'This is my treasure. What is it?',       choices:['It\'s a soccer ball.','It a soccer ball.','Soccer ball is it.','I soccer ball.'],         correct:0 },
    { q:'Are you good at dancing?',               choices:['Yes, I am.','Yes, I good.','Yes, I do.','Yes, I like.'],                                  correct:0 },
    { q:'Hello! I\'m Nadia. What\'s your name?', choices:['Hi! I\'m Daichi.','Hi! I Daichi.','Hi! My am Daichi.','Hi! Daichi I.'],                   correct:0 },
    { q:'What do you like?',                      choices:['I like music.','I wanting music.','Music I like.','I am like music.'],                    correct:0 },
  ],
  2: [
    { q:'What time do you get up?',               choices:['I get up at 6 a.m.','I get up in 6 a.m.','I getted up at 6.','At 6 I get.'],             correct:0 },
    { q:'What time do you go to bed?',            choices:['I usually go to bed at 9 p.m.','I go bed at 9.','I goed to bed 9.','Bed I go 9.'],        correct:0 },
    { q:'Do you always wash the dishes?',         choices:['No, I sometimes wash the dishes.','No, I sometime wash.','No, I washing.','No, sometimes I washed.'], correct:0 },
    { q:'What time do you do your homework?',     choices:['I usually do my homework at 4 p.m.','I homework at 4.','At 4 I homework.','I did homework.'], correct:0 },
    { q:'Do you always play soccer?',             choices:['No, I sometimes play soccer.','No, I sometime soccer.','No, soccer I play.','No, I played always.'], correct:0 },
    { q:'What time do you have breakfast?',       choices:['I always have breakfast at 7 a.m.','I breakfast 7.','At 7 I eat breakfast.','Breakfast I have 7.'], correct:0 },
    { q:'What time do you go to school?',         choices:['I go to school at 8 a.m.','I go school 8.','School I at 8.','I going school 8.'],         correct:0 },
    { q:'Tell me about your daily schedule.',     choices:['I usually get up at 6 a.m.','I everyday 6.','My schedule is 6.','At 6 I am up.'],         correct:0 },
    { q:'What time do you walk your dog?',        choices:['I usually walk my dog at 5 p.m.','I dog walk 5.','5 I walk dog.','I walking dog 5.'],     correct:0 },
    { q:'How was your day?',                      choices:['It was great!','It great was!','Was great it!','Great it was!'],                           correct:0 },
  ],
  3: [
    { q:'How was your weekend?',                  choices:['It was great!','It is great!','It were great!','Is great it!'],                           correct:0 },
    { q:'What did you do on the weekend?',        choices:['I went to the stadium.','I go to the stadium.','I goes to the stadium.','I goed stadium.'], correct:0 },
    { q:'What did you eat?',                      choices:['I ate fried chicken.','I eat fried chicken.','I eating fried chicken.','I eated chicken.'], correct:0 },
    { q:'Where did you go?',                      choices:['I went to the park.','I go to the park.','I goed to park.','Park I went.'],               correct:0 },
    { q:'Was it fun?',                            choices:['Yes, it was fun!','Yes, it is fun!','Yes, it were fun!','Yes, fun it was!'],               correct:0 },
    { q:'What did you enjoy?',                    choices:['I enjoyed watching a rugby game.','I enjoy watching rugby.','I watched enjoy rugby.','Rugby watch I enjoyed.'], correct:0 },
    { q:'How was the food?',                      choices:['It was delicious!','It is delicious!','It were delicious!','Delicious it was!'],           correct:0 },
    { q:'Did you have fun?',                      choices:['Yes, it was great!','Yes, it is great!','Yes, I having fun.','Yes, fun I had.'],           correct:0 },
    { q:'What did you see?',                      choices:['I saw many animals.','I see many animals.','I seeing many animals.','Animals I see.'],     correct:0 },
    { q:'How was your dinner last night?',        choices:['It was fantastic!','It is fantastic!','It were fantastic!','Fantastic was it!'],           correct:0 },
  ],
  4: [
    { q:'Where do you want to go?',               choices:['I want to go to France.','I wanting go France.','France I want go.','I want go to France.'], correct:0 },
    { q:'What can you do in Italy?',              choices:['You can eat pizza.','You can eating pizza.','You eating pizza.','Pizza you can.'],          correct:0 },
    { q:'What\'s this country?',                  choices:['It\'s France.','Is France.','France is it.','This France is.'],                           correct:0 },
    { q:'Is France beautiful?',                   choices:['Yes, it\'s beautiful.','Yes, it beautiful.','Yes, beautiful it.','Yes, France beautiful.'], correct:0 },
    { q:'What can you see in France?',            choices:['You can see the Eiffel Tower.','You see Eiffel Tower.','Eiffel Tower you can.','See Eiffel Tower can.'], correct:0 },
    { q:'Where is this country?',                 choices:['It\'s in Europe.','It in Europe.','Europe is it.','Is Europe it.'],                       correct:0 },
    { q:'Let\'s go to Australia! What can we do?',choices:['We can see koalas.','We seeing koalas.','Koalas we can.','See koalas we.'],                correct:0 },
    { q:'Why do you want to go there?',           choices:['Because I can eat delicious food.','Because delicious food.','Food delicious can I.','I because food.'], correct:0 },
    { q:'What\'s your favorite country?',         choices:['My favorite country is France.','France my favorite.','I favorite France.','France is my favorite country.'], correct:1 },
    { q:'Can you visit museums in France?',       choices:['Yes, you can!','Yes, you can visiting!','Yes, museums can!','Yes, can you!'],              correct:0 },
  ],
  5: [
    { q:'Where is this stapler from?',            choices:['It\'s from Germany.','Is from Germany.','Germany it is.','From Germany is it.'],           correct:0 },
    { q:'Where is this cap from?',                choices:['It\'s from Vietnam.','Is Vietnam from.','Vietnam from it.','From it Vietnam.'],           correct:0 },
    { q:'Is this from Japan?',                    choices:['No, it isn\'t. It\'s from France.','No, it isn\'t from.','Not from Japan it.','No Japan it.'], correct:0 },
    { q:'Where is New Zealand?',                  choices:['It\'s in Oceania.','New Zealand in is.','Is Oceania it.','Oceania in is New Zealand.'],    correct:0 },
    { q:'Tell me about your sandwich.',           choices:['My sandwich is a COT sandwich.','COT sandwich my.','I my sandwich COT.','My is sandwich COT.'], correct:0 },
    { q:'Where is your sweatshirt from?',         choices:['It\'s from New Zealand.','New Zealand from.','From New Zealand is.','Is from it New Zealand.'], correct:0 },
    { q:'Is your water bottle from Japan?',       choices:['Yes, it is!','Yes, it from Japan!','Yes, Japan it is!','Yes, is from Japan!'],             correct:0 },
    { q:'What country is this from?',             choices:['It\'s from Italy.','Italy from it.','It from Italy is.','From Italy is.'],                correct:0 },
    { q:'Can you guess where this is from?',      choices:['I think it\'s from Germany.','I think Germany from.','Germany from think I.','From Germany I think.'], correct:0 },
    { q:'Where is Vietnam?',                      choices:['Vietnam is in Asia.','Vietnam in Asia is.','Is Asia Vietnam in.','In Asia is Vietnam.'],  correct:0 },
  ],
  6: [
    { q:'Where do tigers live?',                  choices:['Tigers live in forests.','Tigers living forests.','In forests tigers.','Tigers forest live.'], correct:0 },
    { q:'Where do pandas live?',                  choices:['Pandas live in forests.','Pandas living forests.','In forests pandas.','Forest pandas live.'], correct:0 },
    { q:'What\'s a big problem?',                 choices:['Hunting is a big problem.','Hunting big problem.','Big problem is hunting.','Is hunting problem.'], correct:0 },
    { q:'What can we do for sea turtles?',        choices:['We can use eco-friendly bags.','We eco-friendly bags.','Eco bags we use.','Use eco bags can we.'], correct:0 },
    { q:'Where do sea turtles live?',             choices:['Sea turtles live in the sea.','Sea turtles sea live.','In sea sea turtles.','Sea live turtles.'], correct:0 },
    { q:'Why are tigers in danger?',              choices:['Because hunting is a big problem.','Because big problem.','Hunting because.','Big problem hunting.'], correct:0 },
    { q:'What can we do for animals?',            choices:['We can reuse plastic bags.','We reuse bags.','Bags reuse we.','Reuse plastic we can.'],    correct:0 },
    { q:'What do you think about global warming?',choices:['I think it\'s a big problem.','Big problem global warming.','I big problem think.','Problem is I think.'], correct:0 },
    { q:'Where do gorillas live?',                choices:['Gorillas live in forests.','Gorillas forests live.','In forests gorillas.','Forest gorillas live.'], correct:0 },
    { q:'Let\'s save the animals! What can we do?', choices:['We can use eco-friendly bags.','We eco bags.','Eco bags use can.','Can we bags eco.'],  correct:0 },
  ],
  7: [
    { q:'What\'s your best memory?',              choices:['My best memory is our school trip.','Best memory is trip.','Trip my best memory.','My memory is trip.'], correct:0 },
    { q:'Where did you go on your school trip?',  choices:['We went to Kyoto.','We goed Kyoto.','To Kyoto we.','Kyoto we goed.'],                     correct:0 },
    { q:'How was Todaiji Temple?',                choices:['It was old and great.','It is old great.','Old great was it.','Great old it was.'],        correct:0 },
    { q:'What did you eat?',                      choices:['We ate ice cream.','We eated ice cream.','Ice cream we ate.','We eat ice cream.'],         correct:0 },
    { q:'How was your school trip?',              choices:['It was fantastic!','It is fantastic!','Fantastic was it!','It were fantastic!'],           correct:0 },
    { q:'What did you see at the zoo?',           choices:['We saw many animals.','We see many animals.','Many animals we saw.','We seed animals.'],   correct:0 },
    { q:'Was your field trip interesting?',       choices:['Yes, it was interesting!','Yes, it is interesting!','Yes, interesting it!','Yes, was interesting!'], correct:0 },
    { q:'What\'s your best memory of elementary school?', choices:['My best memory is our music festival.','My memory music festival.','Music festival best.','Is my memory festival.'], correct:0 },
    { q:'How many deer did you see?',             choices:['We saw many deer.','We see many deer.','Many deer we.','Deer we saw many.'],               correct:0 },
    { q:'How was Kyoto?',                         choices:['It was wonderful!','It is wonderful!','Wonderful was it!','It wonderful was!'],           correct:0 },
  ],
  8: [
    { q:'What do you want to be?',                choices:['I want to be a doctor.','I want be a doctor.','I wanting be doctor.','Doctor want I be.'], correct:0 },
    { q:'What club do you want to join?',         choices:['I want to join the brass band.','I want join brass band.','Brass band want I.','I joining brass band.'], correct:0 },
    { q:'What are you good at?',                  choices:['I\'m good at singing.','I good at singing.','I am good singing.','Singing I am good.'],   correct:0 },
    { q:'What do you want to study?',             choices:['I want to study science.','I wanting study science.','Science study I.','I want science study.'], correct:0 },
    { q:'Are you good at playing the piano?',     choices:['Yes, I am!','Yes, I good!','Yes, piano I am!','Yes, I do!'],                             correct:0 },
    { q:'Why do you want to be a vet?',           choices:['Because I want to help animals.','Because I helping animals.','Animals I help because.','Because help I animals.'], correct:0 },
    { q:'What\'s your dream?',                    choices:['I want to be an international businessperson.','Business want I.','Businessperson I be wanting.','Want I be business.'], correct:0 },
    { q:'Where do you want to work?',             choices:['I want to work in Australia.','I wanting work Australia.','Work Australia I want.','Australia work I want.'], correct:0 },
    { q:'I like animals. What do you want to be?',choices:['I want to be a vet.','I wanting vet.','Vet I be want.','Want I a vet.'],                  correct:0 },
    { q:'Do you like English?',                   choices:['Yes, I like English!','Yes, I liking English!','Yes, English I like!','Yes, I am like English!'], correct:0 },
  ],
};

// ── WRITING PRACTICE ─────────────────────────────────────────────────────
// type: 'letter' (uppercase + lowercase + example word), 'digraph' (two-letter combo), 'word', 'sentence'
const NH6_WRITING = {
  1: [
    { type:'letter',  upper:'B', lower:'b', word:'ball',     emoji:'⚽',  hint:'ボール' },
    { type:'letter',  upper:'C', lower:'c', word:'cat',      emoji:'🐱',  hint:'ねこ' },
    { type:'letter',  upper:'D', lower:'d', word:'dog',      emoji:'🐶',  hint:'いぬ' },
    { type:'letter',  upper:'F', lower:'f', word:'fish',     emoji:'🐟',  hint:'さかな' },
    { type:'letter',  upper:'G', lower:'g', word:'gate',     emoji:'🚪',  hint:'ゲート' },
    { type:'word',    word:'blue',    hint:'青い'},
    { type:'word',    word:'soccer',  hint:'サッカー'},
    { type:'word',    word:'like',    hint:'好き'},
  ],
  2: [
    { type:'letter',  upper:'H', lower:'h', word:'hat',      emoji:'🎩',  hint:'帽子' },
    { type:'letter',  upper:'J', lower:'j', word:'juice',    emoji:'🧃',  hint:'ジュース' },
    { type:'letter',  upper:'L', lower:'l', word:'lion',     emoji:'🦁',  hint:'ライオン' },
    { type:'letter',  upper:'M', lower:'m', word:'mouse',    emoji:'🐭',  hint:'ねずみ' },
    { type:'word',    word:'always',   hint:'いつも'},
    { type:'word',    word:'usually',  hint:'たいてい'},
    { type:'word',    word:'sometimes',hint:'ときどき'},
    { type:'word',    word:'never',    hint:'けっして〜ない'},
  ],
  3: [
    { type:'letter',  upper:'K', lower:'k', word:'king',     emoji:'👑',  hint:'王様' },
    { type:'letter',  upper:'P', lower:'p', word:'pig',      emoji:'🐷',  hint:'ブタ' },
    { type:'letter',  upper:'R', lower:'r', word:'rabbit',   emoji:'🐰',  hint:'うさぎ' },
    { type:'letter',  upper:'S', lower:'s', word:'sun',      emoji:'☀️', hint:'太陽' },
    { type:'word',    word:'went',     hint:'行った (go → went)'},
    { type:'word',    word:'ate',      hint:'食べた (eat → ate)'},
    { type:'word',    word:'great',    hint:'すごい'},
  ],
  4: [
    { type:'letter',  upper:'V', lower:'v', word:'van',      emoji:'🚐',  hint:'バン' },
    { type:'letter',  upper:'W', lower:'w', word:'wolf',     emoji:'🐺',  hint:'オオカミ' },
    { type:'letter',  upper:'X', lower:'x', word:'fox',      emoji:'🦊',  hint:'キツネ' },
    { type:'letter',  upper:'Y', lower:'y', word:'yacht',    emoji:'⛵',  hint:'ヨット' },
    { type:'letter',  upper:'Z', lower:'z', word:'zero',     emoji:'0️⃣', hint:'ゼロ' },
    { type:'word',    word:'beautiful',hint:'美しい'},
    { type:'word',    word:'country',  hint:'国'},
  ],
  5: [
    { type:'letter',  upper:'Q', lower:'q', word:'queen',    emoji:'👸',  hint:'女王' },
    { type:'letter',  upper:'E', lower:'e', word:'egg',      emoji:'🥚',  hint:'たまご' },
    { type:'word',    word:'from',     hint:'〜から'},
    { type:'word',    word:'Italy',    hint:'イタリア'},
    { type:'word',    word:'Japan',    hint:'日本'},
    { type:'word',    word:'France',   hint:'フランス'},
    { type:'sentence', text:'It\'s from Italy.', hint:'それはイタリア産です。' },
    { type:'sentence', text:'Where is it from?', hint:'それはどこから？' },
  ],
  6: [
    { type:'digraph', chars:'ch', word:'cheese',   emoji:'🧀',  hint:'チーズ' },
    { type:'digraph', chars:'sh', word:'shark',    emoji:'🦈',  hint:'サメ' },
    { type:'digraph', chars:'th', word:'three',    emoji:'3️⃣', hint:'3' },
    { type:'digraph', chars:'wh', word:'whale',    emoji:'🐳',  hint:'クジラ' },
    { type:'word',    word:'forest',   hint:'森'},
    { type:'word',    word:'problem',  hint:'問題'},
    { type:'sentence', text:'Tigers live in forests.', hint:'トラは森に住んでいます。' },
    { type:'sentence', text:'We can save the animals.', hint:'私たちは動物を守れる。' },
  ],
  7: [
    { type:'word',    word:'memory',   hint:'思い出'},
    { type:'word',    word:'fantastic',hint:'すばらしい'},
    { type:'word',    word:'wonderful',hint:'すてき'},
    { type:'word',    word:'temple',   hint:'お寺'},
    { type:'sentence', text:'My best memory is our school trip.', hint:'一番の思い出は修学旅行です。' },
    { type:'sentence', text:'We went to Kyoto.',                   hint:'私たちは京都へ行きました。' },
    { type:'sentence', text:'It was fantastic!',                   hint:'すばらしかった！' },
    { type:'sentence', text:'We ate ice cream.',                   hint:'私たちはアイスを食べました。' },
  ],
  8: [
    { type:'word',    word:'doctor',   hint:'医者'},
    { type:'word',    word:'teacher',  hint:'先生'},
    { type:'word',    word:'singer',   hint:'歌手'},
    { type:'word',    word:'scientist',hint:'科学者'},
    { type:'sentence', text:'I want to be a doctor.',    hint:'医者になりたい。' },
    { type:'sentence', text:'I\'m good at singing.',     hint:'歌が得意です。' },
    { type:'sentence', text:'I want to join the chorus.',hint:'合唱部に入りたい。' },
    { type:'sentence', text:'I want to help people.',    hint:'人々を助けたい。' },
  ],
};
